# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHubConn'
        repository: 'sandeepsoprasteria/azuredevopsmavendocker'
        command: 'buildAndPush'
        #Dockerfile: '**/Dockerfile'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: $(tag)